### ISSUE TITLE
Warning: `beets.util.confit is deprecated; use confuse instead`

### ISSUE THREAD

**Issue by Bastes** [adamjakab/BeetsPluginDescribe#4]
### Problem

Using the plugin, I get this warning on every command, before any other output:

```
/homes/my_home/.local/lib/python3.8/site-packages/beets/util/confit.py:21: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
```

This warning appeared after I installed and activated the plugin, and does not when the plugin is not enabled nor installed, but on every command I tried (not just `describe`).

The warning does not seem to have any other consequence so far, all commands including `describe` seem to work fine.

### Setup

* OS: Synology DSM 7.0
* Python version: 3.8.8
* Beets version: 1.5.0
* Turning off other plugins made problem go away (yes/no): no
  turning off all other plugins yield the same result as long as `describe` is on
  turning `describe` off removes the warning

My configuration (output of `beet config`) is:

```yaml
directory: ~/music

library: ~/.config/beets/musiclibrary.db

import:
  move: yes

plugins:
  - describe
  - embedart
  - fetchart
  - lastgenre
  - lyrics
  - rewrite
  - the

paths:
  default: %the{$albumartist}/$album/$track $title

albumart:
  ifempty: yes

fetchart:
  minwidth: 300
  maxwidth: 1000
  enforce_ratio: yes

rewrite:
  artist .*johnny clegg.*: Johnny Clegg
  artist .*hans zimmer.*: Hans Zimmer
  artist .*“weird al” yankovic.*: Weird Al Yankovic
```

My plugin version (output of `beet describe -v`) is:

```text
/homes/my_home/.local/lib/python3.8/site-packages/beets/util/confit.py:21: UserWarning: beets.util.confit is deprecated; use confuse instead
  warnings.warn("beets.util.confit is deprecated; use confuse instead")
describe: Describe(beets-describe) plugin for Beets: v0.0.3
```
